// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: api/proto/message.proto

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageService_SendMessage_FullMethodName              = "/proto.message.MessageService/SendMessage"
	MessageService_SendGroupMessage_FullMethodName         = "/proto.message.MessageService/SendGroupMessage"
	MessageService_PullMessages_FullMethodName             = "/proto.message.MessageService/PullMessages"
	MessageService_GetUnreadCount_FullMethodName           = "/proto.message.MessageService/GetUnreadCount"
	MessageService_PullUnreadMessages_FullMethodName       = "/proto.message.MessageService/PullUnreadMessages"
	MessageService_PullAllUnreadOnLogin_FullMethodName     = "/proto.message.MessageService/PullAllUnreadOnLogin"
	MessageService_MarkPrivateMessageAsRead_FullMethodName = "/proto.message.MessageService/MarkPrivateMessageAsRead"
	MessageService_MarkGroupMessageAsRead_FullMethodName   = "/proto.message.MessageService/MarkGroupMessageAsRead"
	MessageService_PullGroupMessages_FullMethodName        = "/proto.message.MessageService/PullGroupMessages"
)

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义消息服务
type MessageServiceClient interface {
	// 发送一条私聊消息
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	// 发送一条群聊消息
	SendGroupMessage(ctx context.Context, in *SendGroupMessageRequest, opts ...grpc.CallOption) (*SendGroupMessageResponse, error)
	// 拉取消息
	PullMessages(ctx context.Context, in *PullMessagesRequest, opts ...grpc.CallOption) (*PullMessagesResponse, error)
	// 获取未读消息数
	GetUnreadCount(ctx context.Context, in *GetUnreadCountRequest, opts ...grpc.CallOption) (*GetUnreadCountResponse, error)
	// 拉取所有未读消息（新增）
	PullUnreadMessages(ctx context.Context, in *PullUnreadMessagesRequest, opts ...grpc.CallOption) (*PullUnreadMessagesResponse, error)
	// 登录时拉取所有未读消息
	PullAllUnreadOnLogin(ctx context.Context, in *PullAllUnreadOnLoginRequest, opts ...grpc.CallOption) (*PullAllUnreadOnLoginResponse, error)
	// 标记私聊消息已读
	MarkPrivateMessageAsRead(ctx context.Context, in *MarkPrivateMessageAsReadRequest, opts ...grpc.CallOption) (*MarkPrivateMessageAsReadResponse, error)
	// 标记群聊消息已读
	MarkGroupMessageAsRead(ctx context.Context, in *MarkGroupMessageAsReadRequest, opts ...grpc.CallOption) (*MarkGroupMessageAsReadResponse, error)
	// 拉取群聊消息
	PullGroupMessages(ctx context.Context, in *PullGroupMessagesRequest, opts ...grpc.CallOption) (*PullGroupMessagesResponse, error)
}

type messageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServiceClient(cc grpc.ClientConnInterface) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, MessageService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) SendGroupMessage(ctx context.Context, in *SendGroupMessageRequest, opts ...grpc.CallOption) (*SendGroupMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendGroupMessageResponse)
	err := c.cc.Invoke(ctx, MessageService_SendGroupMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) PullMessages(ctx context.Context, in *PullMessagesRequest, opts ...grpc.CallOption) (*PullMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullMessagesResponse)
	err := c.cc.Invoke(ctx, MessageService_PullMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) GetUnreadCount(ctx context.Context, in *GetUnreadCountRequest, opts ...grpc.CallOption) (*GetUnreadCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnreadCountResponse)
	err := c.cc.Invoke(ctx, MessageService_GetUnreadCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) PullUnreadMessages(ctx context.Context, in *PullUnreadMessagesRequest, opts ...grpc.CallOption) (*PullUnreadMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullUnreadMessagesResponse)
	err := c.cc.Invoke(ctx, MessageService_PullUnreadMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) PullAllUnreadOnLogin(ctx context.Context, in *PullAllUnreadOnLoginRequest, opts ...grpc.CallOption) (*PullAllUnreadOnLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullAllUnreadOnLoginResponse)
	err := c.cc.Invoke(ctx, MessageService_PullAllUnreadOnLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) MarkPrivateMessageAsRead(ctx context.Context, in *MarkPrivateMessageAsReadRequest, opts ...grpc.CallOption) (*MarkPrivateMessageAsReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkPrivateMessageAsReadResponse)
	err := c.cc.Invoke(ctx, MessageService_MarkPrivateMessageAsRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) MarkGroupMessageAsRead(ctx context.Context, in *MarkGroupMessageAsReadRequest, opts ...grpc.CallOption) (*MarkGroupMessageAsReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkGroupMessageAsReadResponse)
	err := c.cc.Invoke(ctx, MessageService_MarkGroupMessageAsRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) PullGroupMessages(ctx context.Context, in *PullGroupMessagesRequest, opts ...grpc.CallOption) (*PullGroupMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullGroupMessagesResponse)
	err := c.cc.Invoke(ctx, MessageService_PullGroupMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
// All implementations must embed UnimplementedMessageServiceServer
// for forward compatibility.
//
// 定义消息服务
type MessageServiceServer interface {
	// 发送一条私聊消息
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	// 发送一条群聊消息
	SendGroupMessage(context.Context, *SendGroupMessageRequest) (*SendGroupMessageResponse, error)
	// 拉取消息
	PullMessages(context.Context, *PullMessagesRequest) (*PullMessagesResponse, error)
	// 获取未读消息数
	GetUnreadCount(context.Context, *GetUnreadCountRequest) (*GetUnreadCountResponse, error)
	// 拉取所有未读消息（新增）
	PullUnreadMessages(context.Context, *PullUnreadMessagesRequest) (*PullUnreadMessagesResponse, error)
	// 登录时拉取所有未读消息
	PullAllUnreadOnLogin(context.Context, *PullAllUnreadOnLoginRequest) (*PullAllUnreadOnLoginResponse, error)
	// 标记私聊消息已读
	MarkPrivateMessageAsRead(context.Context, *MarkPrivateMessageAsReadRequest) (*MarkPrivateMessageAsReadResponse, error)
	// 标记群聊消息已读
	MarkGroupMessageAsRead(context.Context, *MarkGroupMessageAsReadRequest) (*MarkGroupMessageAsReadResponse, error)
	// 拉取群聊消息
	PullGroupMessages(context.Context, *PullGroupMessagesRequest) (*PullGroupMessagesResponse, error)
	mustEmbedUnimplementedMessageServiceServer()
}

// UnimplementedMessageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageServiceServer struct{}

func (UnimplementedMessageServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedMessageServiceServer) SendGroupMessage(context.Context, *SendGroupMessageRequest) (*SendGroupMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendGroupMessage not implemented")
}
func (UnimplementedMessageServiceServer) PullMessages(context.Context, *PullMessagesRequest) (*PullMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullMessages not implemented")
}
func (UnimplementedMessageServiceServer) GetUnreadCount(context.Context, *GetUnreadCountRequest) (*GetUnreadCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnreadCount not implemented")
}
func (UnimplementedMessageServiceServer) PullUnreadMessages(context.Context, *PullUnreadMessagesRequest) (*PullUnreadMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullUnreadMessages not implemented")
}
func (UnimplementedMessageServiceServer) PullAllUnreadOnLogin(context.Context, *PullAllUnreadOnLoginRequest) (*PullAllUnreadOnLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullAllUnreadOnLogin not implemented")
}
func (UnimplementedMessageServiceServer) MarkPrivateMessageAsRead(context.Context, *MarkPrivateMessageAsReadRequest) (*MarkPrivateMessageAsReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkPrivateMessageAsRead not implemented")
}
func (UnimplementedMessageServiceServer) MarkGroupMessageAsRead(context.Context, *MarkGroupMessageAsReadRequest) (*MarkGroupMessageAsReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkGroupMessageAsRead not implemented")
}
func (UnimplementedMessageServiceServer) PullGroupMessages(context.Context, *PullGroupMessagesRequest) (*PullGroupMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullGroupMessages not implemented")
}
func (UnimplementedMessageServiceServer) mustEmbedUnimplementedMessageServiceServer() {}
func (UnimplementedMessageServiceServer) testEmbeddedByValue()                        {}

// UnsafeMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceServer will
// result in compilation errors.
type UnsafeMessageServiceServer interface {
	mustEmbedUnimplementedMessageServiceServer()
}

func RegisterMessageServiceServer(s grpc.ServiceRegistrar, srv MessageServiceServer) {
	// If the following call panics, it indicates UnimplementedMessageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageService_ServiceDesc, srv)
}

func _MessageService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_SendGroupMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendGroupMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).SendGroupMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_SendGroupMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).SendGroupMessage(ctx, req.(*SendGroupMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_PullMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).PullMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_PullMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).PullMessages(ctx, req.(*PullMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_GetUnreadCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnreadCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).GetUnreadCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_GetUnreadCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).GetUnreadCount(ctx, req.(*GetUnreadCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_PullUnreadMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullUnreadMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).PullUnreadMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_PullUnreadMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).PullUnreadMessages(ctx, req.(*PullUnreadMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_PullAllUnreadOnLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullAllUnreadOnLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).PullAllUnreadOnLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_PullAllUnreadOnLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).PullAllUnreadOnLogin(ctx, req.(*PullAllUnreadOnLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_MarkPrivateMessageAsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkPrivateMessageAsReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).MarkPrivateMessageAsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_MarkPrivateMessageAsRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).MarkPrivateMessageAsRead(ctx, req.(*MarkPrivateMessageAsReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_MarkGroupMessageAsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkGroupMessageAsReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).MarkGroupMessageAsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_MarkGroupMessageAsRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).MarkGroupMessageAsRead(ctx, req.(*MarkGroupMessageAsReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_PullGroupMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullGroupMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).PullGroupMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_PullGroupMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).PullGroupMessages(ctx, req.(*PullGroupMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageService_ServiceDesc is the grpc.ServiceDesc for MessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.message.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _MessageService_SendMessage_Handler,
		},
		{
			MethodName: "SendGroupMessage",
			Handler:    _MessageService_SendGroupMessage_Handler,
		},
		{
			MethodName: "PullMessages",
			Handler:    _MessageService_PullMessages_Handler,
		},
		{
			MethodName: "GetUnreadCount",
			Handler:    _MessageService_GetUnreadCount_Handler,
		},
		{
			MethodName: "PullUnreadMessages",
			Handler:    _MessageService_PullUnreadMessages_Handler,
		},
		{
			MethodName: "PullAllUnreadOnLogin",
			Handler:    _MessageService_PullAllUnreadOnLogin_Handler,
		},
		{
			MethodName: "MarkPrivateMessageAsRead",
			Handler:    _MessageService_MarkPrivateMessageAsRead_Handler,
		},
		{
			MethodName: "MarkGroupMessageAsRead",
			Handler:    _MessageService_MarkGroupMessageAsRead_Handler,
		},
		{
			MethodName: "PullGroupMessages",
			Handler:    _MessageService_PullGroupMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/message.proto",
}
