// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: friendship/friendship.proto

package friendship

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FriendshipService_SendFriendRequest_FullMethodName       = "/friendship.FriendshipService/SendFriendRequest"
	FriendshipService_GetFriendRequests_FullMethodName       = "/friendship.FriendshipService/GetFriendRequests"
	FriendshipService_ProcessFriendRequest_FullMethodName    = "/friendship.FriendshipService/ProcessFriendRequest"
	FriendshipService_GetFriends_FullMethodName              = "/friendship.FriendshipService/GetFriends"
	FriendshipService_RemoveFriend_FullMethodName            = "/friendship.FriendshipService/RemoveFriend"
	FriendshipService_SendGroupJoinRequest_FullMethodName    = "/friendship.FriendshipService/SendGroupJoinRequest"
	FriendshipService_GetGroupJoinRequests_FullMethodName    = "/friendship.FriendshipService/GetGroupJoinRequests"
	FriendshipService_ProcessGroupJoinRequest_FullMethodName = "/friendship.FriendshipService/ProcessGroupJoinRequest"
	FriendshipService_GetUserGroups_FullMethodName           = "/friendship.FriendshipService/GetUserGroups"
)

// FriendshipServiceClient is the client API for FriendshipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FriendshipServiceClient interface {
	// 好友请求相关
	SendFriendRequest(ctx context.Context, in *SendFriendRequestRequest, opts ...grpc.CallOption) (*SendFriendRequestResponse, error)
	GetFriendRequests(ctx context.Context, in *GetFriendRequestsRequest, opts ...grpc.CallOption) (*GetFriendRequestsResponse, error)
	ProcessFriendRequest(ctx context.Context, in *ProcessFriendRequestRequest, opts ...grpc.CallOption) (*ProcessFriendRequestResponse, error)
	GetFriends(ctx context.Context, in *GetFriendsRequest, opts ...grpc.CallOption) (*GetFriendsResponse, error)
	RemoveFriend(ctx context.Context, in *RemoveFriendRequest, opts ...grpc.CallOption) (*RemoveFriendResponse, error)
	// 群申请相关
	SendGroupJoinRequest(ctx context.Context, in *SendGroupJoinRequestRequest, opts ...grpc.CallOption) (*SendGroupJoinRequestResponse, error)
	GetGroupJoinRequests(ctx context.Context, in *GetGroupJoinRequestsRequest, opts ...grpc.CallOption) (*GetGroupJoinRequestsResponse, error)
	ProcessGroupJoinRequest(ctx context.Context, in *ProcessGroupJoinRequestRequest, opts ...grpc.CallOption) (*ProcessGroupJoinRequestResponse, error)
	// 用户群组相关
	GetUserGroups(ctx context.Context, in *GetUserGroupsRequest, opts ...grpc.CallOption) (*GetUserGroupsResponse, error)
}

type friendshipServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFriendshipServiceClient(cc grpc.ClientConnInterface) FriendshipServiceClient {
	return &friendshipServiceClient{cc}
}

func (c *friendshipServiceClient) SendFriendRequest(ctx context.Context, in *SendFriendRequestRequest, opts ...grpc.CallOption) (*SendFriendRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendFriendRequestResponse)
	err := c.cc.Invoke(ctx, FriendshipService_SendFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendshipServiceClient) GetFriendRequests(ctx context.Context, in *GetFriendRequestsRequest, opts ...grpc.CallOption) (*GetFriendRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFriendRequestsResponse)
	err := c.cc.Invoke(ctx, FriendshipService_GetFriendRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendshipServiceClient) ProcessFriendRequest(ctx context.Context, in *ProcessFriendRequestRequest, opts ...grpc.CallOption) (*ProcessFriendRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessFriendRequestResponse)
	err := c.cc.Invoke(ctx, FriendshipService_ProcessFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendshipServiceClient) GetFriends(ctx context.Context, in *GetFriendsRequest, opts ...grpc.CallOption) (*GetFriendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFriendsResponse)
	err := c.cc.Invoke(ctx, FriendshipService_GetFriends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendshipServiceClient) RemoveFriend(ctx context.Context, in *RemoveFriendRequest, opts ...grpc.CallOption) (*RemoveFriendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFriendResponse)
	err := c.cc.Invoke(ctx, FriendshipService_RemoveFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendshipServiceClient) SendGroupJoinRequest(ctx context.Context, in *SendGroupJoinRequestRequest, opts ...grpc.CallOption) (*SendGroupJoinRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendGroupJoinRequestResponse)
	err := c.cc.Invoke(ctx, FriendshipService_SendGroupJoinRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendshipServiceClient) GetGroupJoinRequests(ctx context.Context, in *GetGroupJoinRequestsRequest, opts ...grpc.CallOption) (*GetGroupJoinRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupJoinRequestsResponse)
	err := c.cc.Invoke(ctx, FriendshipService_GetGroupJoinRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendshipServiceClient) ProcessGroupJoinRequest(ctx context.Context, in *ProcessGroupJoinRequestRequest, opts ...grpc.CallOption) (*ProcessGroupJoinRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessGroupJoinRequestResponse)
	err := c.cc.Invoke(ctx, FriendshipService_ProcessGroupJoinRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendshipServiceClient) GetUserGroups(ctx context.Context, in *GetUserGroupsRequest, opts ...grpc.CallOption) (*GetUserGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserGroupsResponse)
	err := c.cc.Invoke(ctx, FriendshipService_GetUserGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FriendshipServiceServer is the server API for FriendshipService service.
// All implementations must embed UnimplementedFriendshipServiceServer
// for forward compatibility.
type FriendshipServiceServer interface {
	// 好友请求相关
	SendFriendRequest(context.Context, *SendFriendRequestRequest) (*SendFriendRequestResponse, error)
	GetFriendRequests(context.Context, *GetFriendRequestsRequest) (*GetFriendRequestsResponse, error)
	ProcessFriendRequest(context.Context, *ProcessFriendRequestRequest) (*ProcessFriendRequestResponse, error)
	GetFriends(context.Context, *GetFriendsRequest) (*GetFriendsResponse, error)
	RemoveFriend(context.Context, *RemoveFriendRequest) (*RemoveFriendResponse, error)
	// 群申请相关
	SendGroupJoinRequest(context.Context, *SendGroupJoinRequestRequest) (*SendGroupJoinRequestResponse, error)
	GetGroupJoinRequests(context.Context, *GetGroupJoinRequestsRequest) (*GetGroupJoinRequestsResponse, error)
	ProcessGroupJoinRequest(context.Context, *ProcessGroupJoinRequestRequest) (*ProcessGroupJoinRequestResponse, error)
	// 用户群组相关
	GetUserGroups(context.Context, *GetUserGroupsRequest) (*GetUserGroupsResponse, error)
	mustEmbedUnimplementedFriendshipServiceServer()
}

// UnimplementedFriendshipServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFriendshipServiceServer struct{}

func (UnimplementedFriendshipServiceServer) SendFriendRequest(context.Context, *SendFriendRequestRequest) (*SendFriendRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendFriendRequest not implemented")
}
func (UnimplementedFriendshipServiceServer) GetFriendRequests(context.Context, *GetFriendRequestsRequest) (*GetFriendRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFriendRequests not implemented")
}
func (UnimplementedFriendshipServiceServer) ProcessFriendRequest(context.Context, *ProcessFriendRequestRequest) (*ProcessFriendRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessFriendRequest not implemented")
}
func (UnimplementedFriendshipServiceServer) GetFriends(context.Context, *GetFriendsRequest) (*GetFriendsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFriends not implemented")
}
func (UnimplementedFriendshipServiceServer) RemoveFriend(context.Context, *RemoveFriendRequest) (*RemoveFriendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFriend not implemented")
}
func (UnimplementedFriendshipServiceServer) SendGroupJoinRequest(context.Context, *SendGroupJoinRequestRequest) (*SendGroupJoinRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendGroupJoinRequest not implemented")
}
func (UnimplementedFriendshipServiceServer) GetGroupJoinRequests(context.Context, *GetGroupJoinRequestsRequest) (*GetGroupJoinRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupJoinRequests not implemented")
}
func (UnimplementedFriendshipServiceServer) ProcessGroupJoinRequest(context.Context, *ProcessGroupJoinRequestRequest) (*ProcessGroupJoinRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessGroupJoinRequest not implemented")
}
func (UnimplementedFriendshipServiceServer) GetUserGroups(context.Context, *GetUserGroupsRequest) (*GetUserGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserGroups not implemented")
}
func (UnimplementedFriendshipServiceServer) mustEmbedUnimplementedFriendshipServiceServer() {}
func (UnimplementedFriendshipServiceServer) testEmbeddedByValue()                           {}

// UnsafeFriendshipServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FriendshipServiceServer will
// result in compilation errors.
type UnsafeFriendshipServiceServer interface {
	mustEmbedUnimplementedFriendshipServiceServer()
}

func RegisterFriendshipServiceServer(s grpc.ServiceRegistrar, srv FriendshipServiceServer) {
	// If the following call panics, it indicates UnimplementedFriendshipServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FriendshipService_ServiceDesc, srv)
}

func _FriendshipService_SendFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendFriendRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendshipServiceServer).SendFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendshipService_SendFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendshipServiceServer).SendFriendRequest(ctx, req.(*SendFriendRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendshipService_GetFriendRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendshipServiceServer).GetFriendRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendshipService_GetFriendRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendshipServiceServer).GetFriendRequests(ctx, req.(*GetFriendRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendshipService_ProcessFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessFriendRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendshipServiceServer).ProcessFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendshipService_ProcessFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendshipServiceServer).ProcessFriendRequest(ctx, req.(*ProcessFriendRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendshipService_GetFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendshipServiceServer).GetFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendshipService_GetFriends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendshipServiceServer).GetFriends(ctx, req.(*GetFriendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendshipService_RemoveFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendshipServiceServer).RemoveFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendshipService_RemoveFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendshipServiceServer).RemoveFriend(ctx, req.(*RemoveFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendshipService_SendGroupJoinRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendGroupJoinRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendshipServiceServer).SendGroupJoinRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendshipService_SendGroupJoinRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendshipServiceServer).SendGroupJoinRequest(ctx, req.(*SendGroupJoinRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendshipService_GetGroupJoinRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupJoinRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendshipServiceServer).GetGroupJoinRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendshipService_GetGroupJoinRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendshipServiceServer).GetGroupJoinRequests(ctx, req.(*GetGroupJoinRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendshipService_ProcessGroupJoinRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessGroupJoinRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendshipServiceServer).ProcessGroupJoinRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendshipService_ProcessGroupJoinRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendshipServiceServer).ProcessGroupJoinRequest(ctx, req.(*ProcessGroupJoinRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendshipService_GetUserGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendshipServiceServer).GetUserGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendshipService_GetUserGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendshipServiceServer).GetUserGroups(ctx, req.(*GetUserGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FriendshipService_ServiceDesc is the grpc.ServiceDesc for FriendshipService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FriendshipService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "friendship.FriendshipService",
	HandlerType: (*FriendshipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendFriendRequest",
			Handler:    _FriendshipService_SendFriendRequest_Handler,
		},
		{
			MethodName: "GetFriendRequests",
			Handler:    _FriendshipService_GetFriendRequests_Handler,
		},
		{
			MethodName: "ProcessFriendRequest",
			Handler:    _FriendshipService_ProcessFriendRequest_Handler,
		},
		{
			MethodName: "GetFriends",
			Handler:    _FriendshipService_GetFriends_Handler,
		},
		{
			MethodName: "RemoveFriend",
			Handler:    _FriendshipService_RemoveFriend_Handler,
		},
		{
			MethodName: "SendGroupJoinRequest",
			Handler:    _FriendshipService_SendGroupJoinRequest_Handler,
		},
		{
			MethodName: "GetGroupJoinRequests",
			Handler:    _FriendshipService_GetGroupJoinRequests_Handler,
		},
		{
			MethodName: "ProcessGroupJoinRequest",
			Handler:    _FriendshipService_ProcessGroupJoinRequest_Handler,
		},
		{
			MethodName: "GetUserGroups",
			Handler:    _FriendshipService_GetUserGroups_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "friendship/friendship.proto",
}
