// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: friendship/friendship.proto

package friendship

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToUserId      string                 `protobuf:"bytes,1,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 可选备注
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestRequest) Reset() {
	*x = SendFriendRequestRequest{}
	mi := &file_friendship_friendship_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestRequest) ProtoMessage() {}

func (x *SendFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendship_friendship_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*SendFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_friendship_friendship_proto_rawDescGZIP(), []int{0}
}

func (x *SendFriendRequestRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *SendFriendRequestRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendFriendRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestResponse) Reset() {
	*x = SendFriendRequestResponse{}
	mi := &file_friendship_friendship_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestResponse) ProtoMessage() {}

func (x *SendFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friendship_friendship_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*SendFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_friendship_friendship_proto_rawDescGZIP(), []int{1}
}

func (x *SendFriendRequestResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendFriendRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendFriendRequestResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetFriendRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 0=pending, 1=accepted, 2=rejected, 3=cancelled
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendRequestsRequest) Reset() {
	*x = GetFriendRequestsRequest{}
	mi := &file_friendship_friendship_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendRequestsRequest) ProtoMessage() {}

func (x *GetFriendRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendship_friendship_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetFriendRequestsRequest) Descriptor() ([]byte, []int) {
	return file_friendship_friendship_proto_rawDescGZIP(), []int{2}
}

func (x *GetFriendRequestsRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetFriendRequestsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFriendRequestsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type FriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromUserId    string                 `protobuf:"bytes,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	FromUsername  string                 `protobuf:"bytes,3,opt,name=from_username,json=fromUsername,proto3" json:"from_username,omitempty"`
	FromNickname  string                 `protobuf:"bytes,4,opt,name=from_nickname,json=fromNickname,proto3" json:"from_nickname,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"` // 0=pending, 1=accepted, 2=rejected, 3=cancelled
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	mi := &file_friendship_friendship_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendship_friendship_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_friendship_friendship_proto_rawDescGZIP(), []int{3}
}

func (x *FriendRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FriendRequest) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *FriendRequest) GetFromUsername() string {
	if x != nil {
		return x.FromUsername
	}
	return ""
}

func (x *FriendRequest) GetFromNickname() string {
	if x != nil {
		return x.FromNickname
	}
	return ""
}

func (x *FriendRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FriendRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FriendRequest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetFriendRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Requests      []*FriendRequest       `protobuf:"bytes,3,rep,name=requests,proto3" json:"requests,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendRequestsResponse) Reset() {
	*x = GetFriendRequestsResponse{}
	mi := &file_friendship_friendship_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendRequestsResponse) ProtoMessage() {}

func (x *GetFriendRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friendship_friendship_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendRequestsResponse.ProtoReflect.Descriptor instead.
func (*GetFriendRequestsResponse) Descriptor() ([]byte, []int) {
	return file_friendship_friendship_proto_rawDescGZIP(), []int{4}
}

func (x *GetFriendRequestsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetFriendRequestsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetFriendRequestsResponse) GetRequests() []*FriendRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *GetFriendRequestsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ProcessFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Accept        bool                   `protobuf:"varint,2,opt,name=accept,proto3" json:"accept,omitempty"` // true=接受，false=拒绝
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessFriendRequestRequest) Reset() {
	*x = ProcessFriendRequestRequest{}
	mi := &file_friendship_friendship_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessFriendRequestRequest) ProtoMessage() {}

func (x *ProcessFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendship_friendship_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*ProcessFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_friendship_friendship_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessFriendRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProcessFriendRequestRequest) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type ProcessFriendRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessFriendRequestResponse) Reset() {
	*x = ProcessFriendRequestResponse{}
	mi := &file_friendship_friendship_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessFriendRequestResponse) ProtoMessage() {}

func (x *ProcessFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friendship_friendship_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*ProcessFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_friendship_friendship_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessFriendRequestResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ProcessFriendRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendsRequest) Reset() {
	*x = GetFriendsRequest{}
	mi := &file_friendship_friendship_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendsRequest) ProtoMessage() {}

func (x *GetFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendship_friendship_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendsRequest.ProtoReflect.Descriptor instead.
func (*GetFriendsRequest) Descriptor() ([]byte, []int) {
	return file_friendship_friendship_proto_rawDescGZIP(), []int{7}
}

func (x *GetFriendsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFriendsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Friend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 添加时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Friend) Reset() {
	*x = Friend{}
	mi := &file_friendship_friendship_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Friend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friend) ProtoMessage() {}

func (x *Friend) ProtoReflect() protoreflect.Message {
	mi := &file_friendship_friendship_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friend.ProtoReflect.Descriptor instead.
func (*Friend) Descriptor() ([]byte, []int) {
	return file_friendship_friendship_proto_rawDescGZIP(), []int{8}
}

func (x *Friend) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Friend) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Friend) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Friend) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetFriendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Friends       []*Friend              `protobuf:"bytes,3,rep,name=friends,proto3" json:"friends,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendsResponse) Reset() {
	*x = GetFriendsResponse{}
	mi := &file_friendship_friendship_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendsResponse) ProtoMessage() {}

func (x *GetFriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friendship_friendship_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendsResponse.ProtoReflect.Descriptor instead.
func (*GetFriendsResponse) Descriptor() ([]byte, []int) {
	return file_friendship_friendship_proto_rawDescGZIP(), []int{9}
}

func (x *GetFriendsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetFriendsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetFriendsResponse) GetFriends() []*Friend {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *GetFriendsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RemoveFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendUserId  string                 `protobuf:"bytes,1,opt,name=friend_user_id,json=friendUserId,proto3" json:"friend_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendRequest) Reset() {
	*x = RemoveFriendRequest{}
	mi := &file_friendship_friendship_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendRequest) ProtoMessage() {}

func (x *RemoveFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendship_friendship_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendRequest.ProtoReflect.Descriptor instead.
func (*RemoveFriendRequest) Descriptor() ([]byte, []int) {
	return file_friendship_friendship_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveFriendRequest) GetFriendUserId() string {
	if x != nil {
		return x.FriendUserId
	}
	return ""
}

type RemoveFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendResponse) Reset() {
	*x = RemoveFriendResponse{}
	mi := &file_friendship_friendship_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendResponse) ProtoMessage() {}

func (x *RemoveFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friendship_friendship_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendResponse.ProtoReflect.Descriptor instead.
func (*RemoveFriendResponse) Descriptor() ([]byte, []int) {
	return file_friendship_friendship_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveFriendResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RemoveFriendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendGroupJoinRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGroupJoinRequestRequest) Reset() {
	*x = SendGroupJoinRequestRequest{}
	mi := &file_friendship_friendship_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGroupJoinRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupJoinRequestRequest) ProtoMessage() {}

func (x *SendGroupJoinRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendship_friendship_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupJoinRequestRequest.ProtoReflect.Descriptor instead.
func (*SendGroupJoinRequestRequest) Descriptor() ([]byte, []int) {
	return file_friendship_friendship_proto_rawDescGZIP(), []int{12}
}

func (x *SendGroupJoinRequestRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SendGroupJoinRequestRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendGroupJoinRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGroupJoinRequestResponse) Reset() {
	*x = SendGroupJoinRequestResponse{}
	mi := &file_friendship_friendship_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGroupJoinRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupJoinRequestResponse) ProtoMessage() {}

func (x *SendGroupJoinRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friendship_friendship_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupJoinRequestResponse.ProtoReflect.Descriptor instead.
func (*SendGroupJoinRequestResponse) Descriptor() ([]byte, []int) {
	return file_friendship_friendship_proto_rawDescGZIP(), []int{13}
}

func (x *SendGroupJoinRequestResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendGroupJoinRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendGroupJoinRequestResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetGroupJoinRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 0=pending, 1=accepted, 2=rejected, 3=cancelled
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupJoinRequestsRequest) Reset() {
	*x = GetGroupJoinRequestsRequest{}
	mi := &file_friendship_friendship_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupJoinRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupJoinRequestsRequest) ProtoMessage() {}

func (x *GetGroupJoinRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendship_friendship_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupJoinRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetGroupJoinRequestsRequest) Descriptor() ([]byte, []int) {
	return file_friendship_friendship_proto_rawDescGZIP(), []int{14}
}

func (x *GetGroupJoinRequestsRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GetGroupJoinRequestsRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetGroupJoinRequestsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetGroupJoinRequestsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GroupJoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromUserId    string                 `protobuf:"bytes,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	FromUsername  string                 `protobuf:"bytes,3,opt,name=from_username,json=fromUsername,proto3" json:"from_username,omitempty"`
	FromNickname  string                 `protobuf:"bytes,4,opt,name=from_nickname,json=fromNickname,proto3" json:"from_nickname,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	GroupId       string                 `protobuf:"bytes,7,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupJoinRequest) Reset() {
	*x = GroupJoinRequest{}
	mi := &file_friendship_friendship_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupJoinRequest) ProtoMessage() {}

func (x *GroupJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendship_friendship_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupJoinRequest.ProtoReflect.Descriptor instead.
func (*GroupJoinRequest) Descriptor() ([]byte, []int) {
	return file_friendship_friendship_proto_rawDescGZIP(), []int{15}
}

func (x *GroupJoinRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GroupJoinRequest) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *GroupJoinRequest) GetFromUsername() string {
	if x != nil {
		return x.FromUsername
	}
	return ""
}

func (x *GroupJoinRequest) GetFromNickname() string {
	if x != nil {
		return x.FromNickname
	}
	return ""
}

func (x *GroupJoinRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GroupJoinRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GroupJoinRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupJoinRequest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetGroupJoinRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Requests      []*GroupJoinRequest    `protobuf:"bytes,3,rep,name=requests,proto3" json:"requests,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupJoinRequestsResponse) Reset() {
	*x = GetGroupJoinRequestsResponse{}
	mi := &file_friendship_friendship_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupJoinRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupJoinRequestsResponse) ProtoMessage() {}

func (x *GetGroupJoinRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friendship_friendship_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupJoinRequestsResponse.ProtoReflect.Descriptor instead.
func (*GetGroupJoinRequestsResponse) Descriptor() ([]byte, []int) {
	return file_friendship_friendship_proto_rawDescGZIP(), []int{16}
}

func (x *GetGroupJoinRequestsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetGroupJoinRequestsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGroupJoinRequestsResponse) GetRequests() []*GroupJoinRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *GetGroupJoinRequestsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ProcessGroupJoinRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Accept        bool                   `protobuf:"varint,2,opt,name=accept,proto3" json:"accept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessGroupJoinRequestRequest) Reset() {
	*x = ProcessGroupJoinRequestRequest{}
	mi := &file_friendship_friendship_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessGroupJoinRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessGroupJoinRequestRequest) ProtoMessage() {}

func (x *ProcessGroupJoinRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendship_friendship_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessGroupJoinRequestRequest.ProtoReflect.Descriptor instead.
func (*ProcessGroupJoinRequestRequest) Descriptor() ([]byte, []int) {
	return file_friendship_friendship_proto_rawDescGZIP(), []int{17}
}

func (x *ProcessGroupJoinRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProcessGroupJoinRequestRequest) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type ProcessGroupJoinRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessGroupJoinRequestResponse) Reset() {
	*x = ProcessGroupJoinRequestResponse{}
	mi := &file_friendship_friendship_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessGroupJoinRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessGroupJoinRequestResponse) ProtoMessage() {}

func (x *ProcessGroupJoinRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friendship_friendship_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessGroupJoinRequestResponse.ProtoReflect.Descriptor instead.
func (*ProcessGroupJoinRequestResponse) Descriptor() ([]byte, []int) {
	return file_friendship_friendship_proto_rawDescGZIP(), []int{18}
}

func (x *ProcessGroupJoinRequestResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ProcessGroupJoinRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserGroupsRequest) Reset() {
	*x = GetUserGroupsRequest{}
	mi := &file_friendship_friendship_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserGroupsRequest) ProtoMessage() {}

func (x *GetUserGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friendship_friendship_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserGroupsRequest.ProtoReflect.Descriptor instead.
func (*GetUserGroupsRequest) Descriptor() ([]byte, []int) {
	return file_friendship_friendship_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserGroupsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserGroupsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MemberCount   int32                  `protobuf:"varint,4,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	mi := &file_friendship_friendship_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_friendship_friendship_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_friendship_friendship_proto_rawDescGZIP(), []int{20}
}

func (x *GroupInfo) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GroupInfo) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *GroupInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetUserGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Groups        []*GroupInfo           `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserGroupsResponse) Reset() {
	*x = GetUserGroupsResponse{}
	mi := &file_friendship_friendship_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserGroupsResponse) ProtoMessage() {}

func (x *GetUserGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friendship_friendship_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserGroupsResponse.ProtoReflect.Descriptor instead.
func (*GetUserGroupsResponse) Descriptor() ([]byte, []int) {
	return file_friendship_friendship_proto_rawDescGZIP(), []int{21}
}

func (x *GetUserGroupsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserGroupsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserGroupsResponse) GetGroups() []*GroupInfo {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *GetUserGroupsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_friendship_friendship_proto protoreflect.FileDescriptor

const file_friendship_friendship_proto_rawDesc = "" +
	"\n" +
	"\x1bfriendship/friendship.proto\x12\n" +
	"friendship\"R\n" +
	"\x18SendFriendRequestRequest\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x01 \x01(\tR\btoUserId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"h\n" +
	"\x19SendFriendRequestResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"`\n" +
	"\x18GetFriendRequestsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"\xdc\x01\n" +
	"\rFriendRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\tR\n" +
	"fromUserId\x12#\n" +
	"\rfrom_username\x18\x03 \x01(\tR\ffromUsername\x12#\n" +
	"\rfrom_nickname\x18\x04 \x01(\tR\ffromNickname\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"\x96\x01\n" +
	"\x19GetFriendRequestsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\brequests\x18\x03 \x03(\v2\x19.friendship.FriendRequestR\brequests\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"T\n" +
	"\x1bProcessFriendRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06accept\x18\x02 \x01(\bR\x06accept\"L\n" +
	"\x1cProcessFriendRequestResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\x11GetFriendsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"x\n" +
	"\x06Friend\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"\x86\x01\n" +
	"\x12GetFriendsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\afriends\x18\x03 \x03(\v2\x12.friendship.FriendR\afriends\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\";\n" +
	"\x13RemoveFriendRequest\x12$\n" +
	"\x0efriend_user_id\x18\x01 \x01(\tR\ffriendUserId\"D\n" +
	"\x14RemoveFriendResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"R\n" +
	"\x1bSendGroupJoinRequestRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"k\n" +
	"\x1cSendGroupJoinRequestResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"~\n" +
	"\x1bGetGroupJoinRequestsRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\"\xfa\x01\n" +
	"\x10GroupJoinRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\tR\n" +
	"fromUserId\x12#\n" +
	"\rfrom_username\x18\x03 \x01(\tR\ffromUsername\x12#\n" +
	"\rfrom_nickname\x18\x04 \x01(\tR\ffromNickname\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x19\n" +
	"\bgroup_id\x18\a \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"\x9c\x01\n" +
	"\x1cGetGroupJoinRequestsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\brequests\x18\x03 \x03(\v2\x1c.friendship.GroupJoinRequestR\brequests\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"W\n" +
	"\x1eProcessGroupJoinRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06accept\x18\x02 \x01(\bR\x06accept\"O\n" +
	"\x1fProcessGroupJoinRequestResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"D\n" +
	"\x14GetUserGroupsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"\xa9\x01\n" +
	"\tGroupInfo\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\fmember_count\x18\x04 \x01(\x05R\vmemberCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"\x8a\x01\n" +
	"\x15GetUserGroupsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x06groups\x18\x03 \x03(\v2\x15.friendship.GroupInfoR\x06groups\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total2\x82\a\n" +
	"\x11FriendshipService\x12`\n" +
	"\x11SendFriendRequest\x12$.friendship.SendFriendRequestRequest\x1a%.friendship.SendFriendRequestResponse\x12`\n" +
	"\x11GetFriendRequests\x12$.friendship.GetFriendRequestsRequest\x1a%.friendship.GetFriendRequestsResponse\x12i\n" +
	"\x14ProcessFriendRequest\x12'.friendship.ProcessFriendRequestRequest\x1a(.friendship.ProcessFriendRequestResponse\x12K\n" +
	"\n" +
	"GetFriends\x12\x1d.friendship.GetFriendsRequest\x1a\x1e.friendship.GetFriendsResponse\x12Q\n" +
	"\fRemoveFriend\x12\x1f.friendship.RemoveFriendRequest\x1a .friendship.RemoveFriendResponse\x12i\n" +
	"\x14SendGroupJoinRequest\x12'.friendship.SendGroupJoinRequestRequest\x1a(.friendship.SendGroupJoinRequestResponse\x12i\n" +
	"\x14GetGroupJoinRequests\x12'.friendship.GetGroupJoinRequestsRequest\x1a(.friendship.GetGroupJoinRequestsResponse\x12r\n" +
	"\x17ProcessGroupJoinRequest\x12*.friendship.ProcessGroupJoinRequestRequest\x1a+.friendship.ProcessGroupJoinRequestResponse\x12T\n" +
	"\rGetUserGroups\x12 .friendship.GetUserGroupsRequest\x1a!.friendship.GetUserGroupsResponseB\x1dZ\x1bChatIM/api/proto/friendshipb\x06proto3"

var (
	file_friendship_friendship_proto_rawDescOnce sync.Once
	file_friendship_friendship_proto_rawDescData []byte
)

func file_friendship_friendship_proto_rawDescGZIP() []byte {
	file_friendship_friendship_proto_rawDescOnce.Do(func() {
		file_friendship_friendship_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_friendship_friendship_proto_rawDesc), len(file_friendship_friendship_proto_rawDesc)))
	})
	return file_friendship_friendship_proto_rawDescData
}

var file_friendship_friendship_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_friendship_friendship_proto_goTypes = []any{
	(*SendFriendRequestRequest)(nil),        // 0: friendship.SendFriendRequestRequest
	(*SendFriendRequestResponse)(nil),       // 1: friendship.SendFriendRequestResponse
	(*GetFriendRequestsRequest)(nil),        // 2: friendship.GetFriendRequestsRequest
	(*FriendRequest)(nil),                   // 3: friendship.FriendRequest
	(*GetFriendRequestsResponse)(nil),       // 4: friendship.GetFriendRequestsResponse
	(*ProcessFriendRequestRequest)(nil),     // 5: friendship.ProcessFriendRequestRequest
	(*ProcessFriendRequestResponse)(nil),    // 6: friendship.ProcessFriendRequestResponse
	(*GetFriendsRequest)(nil),               // 7: friendship.GetFriendsRequest
	(*Friend)(nil),                          // 8: friendship.Friend
	(*GetFriendsResponse)(nil),              // 9: friendship.GetFriendsResponse
	(*RemoveFriendRequest)(nil),             // 10: friendship.RemoveFriendRequest
	(*RemoveFriendResponse)(nil),            // 11: friendship.RemoveFriendResponse
	(*SendGroupJoinRequestRequest)(nil),     // 12: friendship.SendGroupJoinRequestRequest
	(*SendGroupJoinRequestResponse)(nil),    // 13: friendship.SendGroupJoinRequestResponse
	(*GetGroupJoinRequestsRequest)(nil),     // 14: friendship.GetGroupJoinRequestsRequest
	(*GroupJoinRequest)(nil),                // 15: friendship.GroupJoinRequest
	(*GetGroupJoinRequestsResponse)(nil),    // 16: friendship.GetGroupJoinRequestsResponse
	(*ProcessGroupJoinRequestRequest)(nil),  // 17: friendship.ProcessGroupJoinRequestRequest
	(*ProcessGroupJoinRequestResponse)(nil), // 18: friendship.ProcessGroupJoinRequestResponse
	(*GetUserGroupsRequest)(nil),            // 19: friendship.GetUserGroupsRequest
	(*GroupInfo)(nil),                       // 20: friendship.GroupInfo
	(*GetUserGroupsResponse)(nil),           // 21: friendship.GetUserGroupsResponse
}
var file_friendship_friendship_proto_depIdxs = []int32{
	3,  // 0: friendship.GetFriendRequestsResponse.requests:type_name -> friendship.FriendRequest
	8,  // 1: friendship.GetFriendsResponse.friends:type_name -> friendship.Friend
	15, // 2: friendship.GetGroupJoinRequestsResponse.requests:type_name -> friendship.GroupJoinRequest
	20, // 3: friendship.GetUserGroupsResponse.groups:type_name -> friendship.GroupInfo
	0,  // 4: friendship.FriendshipService.SendFriendRequest:input_type -> friendship.SendFriendRequestRequest
	2,  // 5: friendship.FriendshipService.GetFriendRequests:input_type -> friendship.GetFriendRequestsRequest
	5,  // 6: friendship.FriendshipService.ProcessFriendRequest:input_type -> friendship.ProcessFriendRequestRequest
	7,  // 7: friendship.FriendshipService.GetFriends:input_type -> friendship.GetFriendsRequest
	10, // 8: friendship.FriendshipService.RemoveFriend:input_type -> friendship.RemoveFriendRequest
	12, // 9: friendship.FriendshipService.SendGroupJoinRequest:input_type -> friendship.SendGroupJoinRequestRequest
	14, // 10: friendship.FriendshipService.GetGroupJoinRequests:input_type -> friendship.GetGroupJoinRequestsRequest
	17, // 11: friendship.FriendshipService.ProcessGroupJoinRequest:input_type -> friendship.ProcessGroupJoinRequestRequest
	19, // 12: friendship.FriendshipService.GetUserGroups:input_type -> friendship.GetUserGroupsRequest
	1,  // 13: friendship.FriendshipService.SendFriendRequest:output_type -> friendship.SendFriendRequestResponse
	4,  // 14: friendship.FriendshipService.GetFriendRequests:output_type -> friendship.GetFriendRequestsResponse
	6,  // 15: friendship.FriendshipService.ProcessFriendRequest:output_type -> friendship.ProcessFriendRequestResponse
	9,  // 16: friendship.FriendshipService.GetFriends:output_type -> friendship.GetFriendsResponse
	11, // 17: friendship.FriendshipService.RemoveFriend:output_type -> friendship.RemoveFriendResponse
	13, // 18: friendship.FriendshipService.SendGroupJoinRequest:output_type -> friendship.SendGroupJoinRequestResponse
	16, // 19: friendship.FriendshipService.GetGroupJoinRequests:output_type -> friendship.GetGroupJoinRequestsResponse
	18, // 20: friendship.FriendshipService.ProcessGroupJoinRequest:output_type -> friendship.ProcessGroupJoinRequestResponse
	21, // 21: friendship.FriendshipService.GetUserGroups:output_type -> friendship.GetUserGroupsResponse
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_friendship_friendship_proto_init() }
func file_friendship_friendship_proto_init() {
	if File_friendship_friendship_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_friendship_friendship_proto_rawDesc), len(file_friendship_friendship_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_friendship_friendship_proto_goTypes,
		DependencyIndexes: file_friendship_friendship_proto_depIdxs,
		MessageInfos:      file_friendship_friendship_proto_msgTypes,
	}.Build()
	File_friendship_friendship_proto = out.File
	file_friendship_friendship_proto_goTypes = nil
	file_friendship_friendship_proto_depIdxs = nil
}
